### ISSUE TITLE
为什么启动不了项目，新手求解

### ISSUE THREAD

**Issue by susang233** [kawa-fe/kawa-resume#37]
pnpm start以后报错
 ERR_PNPM_NO_SCRIPT_OR_SERVER  Missing script start or file server.js
上网搜说是因为没有显示的启动文件，请问需要启动哪个文件

**Comment by LofiSu** [comment]
启动是没问题的，报错信息太少我也不能判断是什么问题

**Comment by LofiSu** [comment]
可以移步到discuss去讨论

**Comment by susang233** [comment]
好的

> 可以移步到discuss去讨论
